/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static db.db_connection.st;
import java.awt.event.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.event.*;
import javax.swing.text.*;

/**
 *
 * @author aishna
 */
public class NewRegisteration extends javax.swing.JFrame {

    /**
     * Creates new form NewRegisteration
     */
    public NewRegisteration() {
        initComponents();
        new TextPrompt("Name",Name);
        new TextPrompt("colleage referral ID",referral);
        new TextPrompt("New Password",newpassword);
        new TextPrompt("Confirm New Password",confirmnewpassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        referral = new javax.swing.JTextField();
        newpassword = new javax.swing.JPasswordField();
        confirmnewpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Account : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        confirmnewpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmnewpasswordActionPerformed(evt);
            }
        });
        confirmnewpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmnewpasswordKeyPressed(evt);
            }
        });

        jButton1.setText("Create New Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(referral, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newpassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmnewpassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(referral, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmnewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //new registeration form
        //create new accounnt button function
        try {
            String New_name=Name.getText();
            String reference=referral.getText();
            String new_password=String.valueOf(newpassword.getPassword());
            String confirm_new_password=String.valueOf(confirmnewpassword.getPassword());
            ResultSet rs = st.executeQuery("select * from login_db where username='"+reference+"'");
            if(rs.next())
            {
                if(new_password.equals(confirm_new_password)){
                    try{
                        db.db_connection.createnewaccount.setString(1,New_name);
                        db.db_connection.createnewaccount.setString(2,confirm_new_password);
                        db.db_connection.createnewaccount.executeUpdate();
                        JOptionPane.showMessageDialog(null,"succesful registeration ! ");
                        db.db_connection.NAME=New_name;
                        dispose();
                        Manage_Canteen_Items MCI=new Manage_Canteen_Items();
                        MCI.setVisible(true);
                        MCI.setLocationRelativeTo(null);
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,"registeration Failed !");
                        Name.setText("");
                        referral.setText("");
                        newpassword.setText("");
                        confirmnewpassword.setText("");
                    }
                }  
                else{
                    JOptionPane.showMessageDialog(null, "New Password and Confirm New Password Not same!");
                    Name.setText("");
                    referral.setText("");
                    newpassword.setText("");
                    confirmnewpassword.setText("");
                }
            }
            else if((New_name.equals("") || reference.equals("") || new_password.equals("") || confirm_new_password.equals("")))
            {
                JOptionPane.showMessageDialog(null, "Invalid Credentials !");
                Name.setText("");
                referral.setText("");
                newpassword.setText("");
                confirmnewpassword.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Not a referral !");
                Name.setText("");
                referral.setText("");
                newpassword.setText("");
                confirmnewpassword.setText("");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //bACK button to login 
        dispose();
        Login nr=new Login();
        nr.setVisible(true);
        nr.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //home button 
        //back to login frame page
        dispose();
        login_frame nr=new login_frame();
        nr.setVisible(true);
        nr.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void confirmnewpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmnewpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmnewpasswordKeyPressed

    private void confirmnewpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmnewpasswordActionPerformed
        // TODO add your handling code here:
        //enterkeylistener
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_confirmnewpasswordActionPerformed

    /**
     * @param args the command line arguments
     */


class TextPrompt extends JLabel implements FocusListener, DocumentListener {
  JTextComponent component;
  Document document;

  public TextPrompt(String text, JTextComponent component) {
    this.component = component;
    document = component.getDocument();

    setText(text);
    setFont(component.getFont());
    setBorder(new EmptyBorder(component.getInsets()));

    component.addFocusListener(this);
    document.addDocumentListener(this);

    component.add(this);
  }

  public void checkForPrompt() {
    if (document.getLength() == 0)
      setSize(component.getSize());
    else
      setSize(0, 0);
  }

  public void focusGained(FocusEvent e) {
    checkForPrompt();
    setForeground(new java.awt.Color(153, 153, 153));
  }

  public void focusLost(FocusEvent e) {
    setSize(0, 0);
  }


  public void insertUpdate(DocumentEvent e) {
    checkForPrompt();
  }
  public void removeUpdate(DocumentEvent e) {
    checkForPrompt();
  }
  public void changedUpdate(DocumentEvent e) {
  }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField confirmnewpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JTextField referral;
    // End of variables declaration//GEN-END:variables
}
